### ISSUE TITLE
Cache MPI build in .travis.yml

### ISSUE THREAD

**Issue by jwscook** [ScottishCovidResponse/SCRCIssueTracking#87]
Supersedes #23 

This post explains how to https://www.aithercfd.com/2016/12/03/using-travisci.html cache things for the next run. This will help things go faster without leaning on a docker image.

```yml
cache:
  directories:
    - <mpi-directory>
    - ~/.julia
```

It would be good to add an `after_script` like this yml psudocode:

```yml
after_script:
  run: rm -rf ~/.julia/packages/Simulation
```

so that Simulation doesn't get cached for next time and we definitely get a clean copy.
